name: Deploy Node.js Server for VPMS

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to server
        run: |
          ssh -o StrictHostKeyChecking=no vpmsadmin@${{ secrets.SERVER_IP }} << 'EOF'
          cd Vocational-Placement-Management-BACKEND
          git pull origin production
          npm install
          npm run build
          pm2 restart my-app || pm2 start dist/server.js --name vpms-server
          EOF
